### ISSUE TITLE
Early loading screen loading sequence triggers load of Minecraft classes prior to launch

### ISSUE THREAD

**Issue by cpw** [neoforged/FancyModLoader#17]
DisplayWindow forces minecraft classes to load too early in the "updateModuleReads" method. This needs to be refactored to not classload anything prior to actual launch.

**Comment by Technici4n** [comment]
How problematic is this in practice?

**Comment by marchermans** [comment]
> How problematic is this in practice?

Those classes are not coremoddable

**Comment by Technici4n** [comment]
Interesting - they should be on the game layer already, so I would have expected them to be coremoddable.

**Comment by Technici4n** [comment]
I just tested and `NeoForgeLoadingOverlay` can be targeted fine with a mixin. @cpw can you elaborate on the issue?
