### ISSUE TITLE
Renaming mods.toml

### ISSUE THREAD

**Issue by kb-1000** [neoforged/FancyModLoader#45]
Calling it mods.toml is fairly ambiguous for various reasons. First, of course, mods.toml is already commonly associated with Lex' Forge, and NeoForge is not compatible with Forge mods. But even ignoring Forge this is ambiguous, just like the index.json in the initial Modrinth pack draft (which was later renamed to index.modrinth.json after I mentioned that).
It should be renamed to something clearly identifying it as NeoForge (following the Modrinth example, mods.neoforge.toml would be an idea, but it could be something else as well)

**Comment by Technici4n** [comment]
Disagree, allowing multiple loaders with a single jar is not a goal and this doesn't stop you from technically achieving it.

**Comment by kb-1000** [comment]
That's not the only reason why you would do that.
But, are there any good reasons for _not_ doing that?

**Comment by Gaming32** [comment]
Having Forge and NeoForge use the same filename makes it quite a lot harder for external applications to check whether a mod is from Forge or NeoForge. If the filenames are different, the application simply has to check for the files. If the filename is the same, the external application now not only has to be able to list jar contents, but has to read jar files and parse TOML.
