### ISSUE TITLE
`ModConfig::getHandler` has gone missing

### ISSUE THREAD

**Issue by Fuzss** [neoforged/FancyModLoader#69]
`ModConfig::getHandler` was used to get an implementation of `ConfigFileTypeHandler` for a specific `ModConfig`.
In #40 all invocations of that method have been inlined with `ConfigFileTypeHandler#TOML`.

The ability to return a custom file handler instance extending `ConfigFileTypeHandler` was useful to me, as it allowed to alter some behavior, mainly placing my server config files in `.minecraft/config` so they can be used globally instead of relying on the default local placement in `.minecraft/saves/<world>/serverconfig`.
https://github.com/Fuzss/puzzleslib/blob/98f507fdaf1fa4c33eb8e783d3713f15e231af24/1.20.1/Forge/src/main/java/fuzs/puzzleslib/impl/config/core/ForgeConfigFileTypeHandler.java#L73

I'm also aware that the Corail Woodcutter mod uses this method, since I got the idea from there: https://github.com/Corail31/woodcutter/blob/1.20/src/main/java/ovh/corail/woodcutter/config/CustomConfig.java

Getting `ModConfig::getHandler` back would be much appreciated, as there is no reason `ConfigFileTypeHandler#TOML` has to be inlined everywhere.
Alternatively giving [this suggestion](https://github.com/MinecraftForge/MinecraftForge/issues/9465) another thought would also solve this issue for me (since implementing that change to the server config file path is the main purpose of my custom `ConfigFileTypeHandler`).

**Comment by Technici4n** [comment]
The behavior you want is now the default: https://github.com/neoforged/NeoForge/pull/376, therefore it is not useful to provide a custom file type handler.

**Comment by Fuzss** [comment]
Thanks, that's great!

**Comment by endorh** [comment]
I used to subclass `ModConfig` to get away with YAML configs and custom comment parsing (preserving user comments while keeping documentation comments (starting with `##`) up to date and translated).

In order to keep compatibility with previous versions of my mods' configs without this extension point, the only option I can see amounts to replicating my own `ConfigTracker`, which doesn't really amuse me.

Is there any reason for this change I'm not aware of, other than simplifying the configs? (judging from the intent of #40)

**Comment by Technici4n** [comment]
Other formats were not meant to be used in the first place. The Forge config system is TOML only.

**Comment by endorh** [comment]
Well, I'd say it was night-config only until now, which allowed for arbitrary formats without much trouble, but I understand.

At least this opportunity will help make my config framework easier to port in the future.
