### ISSUE TITLE
`IModLanguageProvider#loadMod` signature is really weird

### ISSUE THREAD

**Issue by Technici4n** [neoforged/FancyModLoader#72]
The signature is:
```java
    interface IModLanguageLoader {
        <T> T loadMod(IModInfo info, ModFileScanData modFileScanResults, ModuleLayer layer);
    }
```
however `T` should actually be `ModContainer`, which is NOT part of the SPI. A bit tricky to handle I think.

**Comment by Matyrobbrt** [comment]
Fixed in https://github.com/neoforged/FancyModLoader/commit/9cf72d00761abaaeddbe3911c7919da52f068882
