### ISSUE TITLE
[Suggestion]: Increase modid size limit to 256 or more

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/FancyModLoader#78]
If I want the biggest and most bloated modid, dangit I'll get it! It's my right to put in modids that causes people to have to buy a horizontal scrolling mouse! UI sizes? pfff just go off screen! All that has to change is these 2 regex right here
https://github.com/neoforged/FancyModLoader/blob/697a95e1afa858d479dbc96814c0e82c13f02437/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModInfo.java#L33-L34

Embrace the freedom! U N L I M I T E D  M O D I D S

(Note, I am joking lol. But wanted to kick start convo on if this limit is actually needed or if it was just some legacy limit. Datapacks themselves don't have the 63 character namespace limit iirc)

**Comment by PaintNinja** [comment]
In all seriousness, what's the rationale behind wanting a larger limit besides "vanilla datapacks don't have this"?

**Comment by embeddedt** [comment]
There are 3.6 x 10^90 possible 64-character mod IDs using only the letters a-z (not even counting the option to use numbers). That's more than 4 billion, meaning you wouldn't be able to store them all in any array-based data structure... I'm skeptical this would ever become a problem in practice.

**Comment by PaintNinja** [comment]
Increasing the *min* mod ID length to two characters however... That might be worth considering to avoid clashes

**Comment by TelepathicGrunt** [comment]
> In all seriousness, what's the rationale behind wanting a larger limit besides "vanilla datapacks don't have this"?

Does there need to be? How about reversing the question here. If it is an arbitrary limit and not actually required for anything, what is the rational for having the limit in the first place? 

I was making a datapack-turned-mod lowcode mod. It is a compat datapack between two mods. So the modid started off as the name of the two mods + compat. `repurposed_structures_yungs_better_desert_temples`. Then I have a second form of the datapack that instead of overriding the original pyramids from my mod, it keeps both variants. Which then would formed the bigger modid of `repurposed_structures_yungs_better_desert_temples_with_small_pyramids_compat` over 63 limit. I am adjusting it to be `repurposed_structures_better_desert_temples_w_small_pyramids_compat` to be under limit. 

But the limit itself seems silly to have in first place imo.

**Comment by embeddedt** [comment]
From a performance perspective - keep in mind that there are often a lot of `ResourceLocation` objects hanging out in memory, and they don't get interned (unlike `ResourceKey`s), so encouraging the use of larger namespaces means increased memory usage unless a mod adds `ResourceLocation` deduplication, which has a speed penalty.

**Comment by XFactHD** [comment]
> Increasing the min mod ID length to two characters however... That might be worth considering to avoid clashes

The minimum length is already 2 due to how the regexes are set up.

**Comment by TelepathicGrunt** [comment]
> From a performance perspective - keep in mind that there are often a lot of `ResourceLocation` objects hanging out in memory, and they don't get interned (unlike `ResourceKey`s), so encouraging the use of larger namespaces means increased memory usage unless a mod adds `ResourceLocation` deduplication, which has a speed penalty.

Ah fair, That is a point

**Comment by TelepathicGrunt** [comment]
Closing as memory usage is a strong argument to not remove limit
