### ISSUE TITLE
Language provider errors are ignored

### ISSUE THREAD

**Issue by Gaming32** [neoforged/FancyModLoader#89]
If a language provider isn't present, an errors list is created and passed to the sorter.

https://github.com/neoforged/FancyModLoader/blob/9b239e3414695ee2ab49ad6cc9aa96484db456de/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModValidator.java#L99-L104

However, `ModSorter.sort` completely ignores its second argument, leading to missing language providers (`modLoader`s) simply skipping mods with no more than a logged error message. The language can't even be put into `dependencies`, because mods with erroring language providers get entirely removed from the mod list (before dependencies are checked).

**Comment by Matyrobbrt** [comment]
Fixed in https://github.com/neoforged/FancyModLoader/commit/084489886545a9afbf6e82bd90c590d79cb911f0
